# BASE IMAGE
FROM mysql

# Environment Variables : ENV KEY=VALUE
ENV MYSQL_USER=ssar
ENV MYSQL_PASSWORD=ssar1234
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=ssardb

# option
CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
